% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 16-Oct-2025 11:06:21
%
% This script assumes these variables are defined:
%
%   X - input data.
%   Y - target data.


%% Import Data 

close all
data = readmatrix("./python/v2_sensor/calibration_data_s1.txt",'NumHeaderLines',1);

X = data(1:2.3e5,8:11);
Y = data(1:2.3e5,2:4);

% SOrt X and Y values first vy z, then vy x, then by y
% [~,sortidx] = sortrows(Y,[3,1,2]);
% X = X(sortidx,:);
% Y = Y(sortidx,:);

d = designfilt("lowpassfir", ...
    PassbandFrequency=0.30,StopbandFrequency=0.4, ...
    PassbandRipple=1,StopbandAttenuation=60, ...
    DesignMethod="equiripple");

L0 = X(:,1);
L1 = X(:,2);
L2 = X(:,3);
L3 = X(:,4);

L0f = filtfilt(d,L0);
L1f = filtfilt(d,L1);
L2f = filtfilt(d,L2);
L3f = filtfilt(d,L3);

X = [L0,L1,L2,L3];
Xf = [L0f,L1f,L2f,L3f];

Lx = (L0+L1)-(L2+L3);
Ly = (L1+L2)-(L3+L0);
Lz = L0+L1+L2+L3;

X2 = [Lx,Ly,Lz];


x = X';
t = Y';

figure
plot(X)
figure
plot(Y)


%% Setup NNet
% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Levenberg-Marquardt backpropagation.


% Create a Fitting Network
hiddenLayerSize = [10,10,10];
net2 = feedforwardnet(hiddenLayerSize);

% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
net2.input.processFcns = {'removeconstantrows','mapminmax'};
net2.output.processFcns = {'removeconstantrows','mapminmax'};

% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivision
net2.divideFcn = 'dividerand';  % Divide data randomly
net2.divideMode = 'sample';  % Divide up every sample
net2.divideParam.trainRatio = 70/100;
net2.divideParam.valRatio = 30/100;
net2.divideParam.testRatio = 30/100;

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
net2.performFcn = 'mse';  % Mean Squared Error

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
net2.plotFcns = {'plotperform','plottrainstate','ploterrhist', ...
    'plotregression', 'plotfit'};

%% Train the Network
net2.trainFcn = 'trainlm';
net2.trainParam.epochs = 250E3;
net2.trainParam.goal = 0;
net2.trainParam.max_fail = 10;

[net2,tr] = train(net2, x, t,'useGPU','no','showResources','yes');%, 'showResources','yes');%;%)%

%% Test the Network
y = net2(x);
e = gsubtract(t,y);
performance = perform(net2,t,y)

% Recalculate Training, Validation and Test Performance
trainTargets = t .* tr.trainMask{1};
valTargets = t .* tr.valMask{1};
testTargets = t .* tr.testMask{1};
trainPerformance = perform(net2,trainTargets,y)
valPerformance = perform(net2,valTargets,y)
testPerformance = perform(net2,testTargets,y)

% View the Network
view(net2)
% 
net = net2
% save('net.mat', 'net');


% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)
figure; plot(y'-Y);% figure; plot(Y);

% genFunction(net2.Network,'CrackSensorCalib');

figure; plot(y');
% Deployment
% Change the (false) values to (true) to enable the following code blocks.
% See the help for each generation function for more information.
% if (false)
    % Generate MATLAB function for neural network for application
    % deployment in MATLAB scripts or with MATLAB Compiler and Builder
    % tools, or simply to examine the calculations your trained neural
    % network performs.
    genFunction(net2,'CivilSensorCalibv2');
    y_v2 = CivilSensorCalibv2(x);
% end
% if (false)
%     % Generate a matrix-only MATLAB function for neural network code
%     % generation with MATLAB Coder tools.
%     genFunction(net2,'myNeuralNetworkFunction','MatrixOnly','yes');
%     y = myNeuralNetworkFunction(x);
% end
% if (false)
%     % Generate a Simulink diagram for simulation or deployment with.
%     % Simulink Coder tools.
%     gensim(net2);
% end
% Validation for 0 degrees
datav = readmatrix("validation_data_new_0deg.txt",'NumHeaderLines',1);

Xv = datav(:,8:11);
Yv = datav(:,2:4);

yv = net(Xv');
error_0deg = yv' - Yv;

% Validation for 2.5 degrees
datav_2_5deg = readmatrix("validation_data_new_2-5deg.txt",'NumHeaderLines',1);

Xv_2_5deg = datav_2_5deg(:,8:11);
Yv_2_5deg = datav_2_5deg(:,2:4);

yv_2_5deg = net(Xv_2_5deg');
error_2_5deg = yv_2_5deg' - Yv_2_5deg;

% Validation for 5 degrees
datav_5deg = readmatrix("validation_data_new_5deg.txt",'NumHeaderLines',1);

Xv_5deg = datav_5deg(:,8:11);
Yv_5deg = datav_5deg(:,2:4);

yv_5deg = net(Xv_5deg');
error_5deg = yv_5deg' - Yv_5deg;

% Combine errors and data for visualization
errors = {error_0deg, error_2_5deg, error_5deg};
Yvs = {Yv, Yv_2_5deg, Yv_5deg};
yvs = {yv, yv_2_5deg, yv_5deg};
titles = {'Error for 0 degrees', 'Error for 2.5 degrees', 'Error for 5 degrees'};

% Plot errors over space with consistent color scale
figure;

% Determine the global maximum error norm for consistent color scaling
global_max_error = max(cellfun(@(err) max(vecnorm(err, 2, 2)), errors));

for i = 1:3
    error = errors{i};
    Yv_current = Yvs{i};
    subplot(1, 3, i);
    scatter3(Yv_current(:,1), Yv_current(:,2), Yv_current(:,3), 50, vecnorm(error, 2, 2), 'filled');
    colorbar;
    xlabel('X');
    ylabel('Y');
    zlabel('Z');
    title(titles{i});
    caxis([0, global_max_error]); % Use global maximum for color scale
end

figure
for i = 1:3
    error = errors{i};
    yv_current = yvs{i};
    subplot(3, 2, 2*(i-1)+1);
    plot(yv_current')
    colorbar;
    ylabel('Position');
    title(titles{i});
    subplot(3, 2, 2*(i-1)+2);
    plot(yv_current')
    colorbar;
    ylabel('Position Error');
    title(titles{i});


end

