; PlatformIO Project Configuration File

[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
platform_packages =
  framework-arduino-pico @ https://github.com/earlephilhower/arduino-pico.git
board_build.filesystem_size = 0.5m

monitor_speed = 115200

lib_extra_dirs = lib/LDC1614-library

upload_protocol = picotool